name: gachon_noti_front
description: "Gachon University Notice Service"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  web: ^1.1.1
  pwa_install:
    git:
      url: https://github.com/jtmuller5/pwa_install.git
      ref: 82320a2
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17
  flutter_auto_size_text: ^4.1.0
  package_info_plus: ^8.3.0
  intl: ^0.20.2
  http: ^1.3.0
  supabase_flutter: ^2.8.4
  get: ^4.7.2

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/