name: gachon_noti_front
description: "Gachon University Notice Service"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  appwrite: ^15.0.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  web: ^1.1.1
  pwa_install:
    git:
      url: https://github.com/jtmuller5/pwa_install.git
      ref: 82320a2
  pwa_update_listener:
    git:
      url: https://github.com/kjm0202/pwa_update_listener.git
      ref: master
  url_launcher: ^6.3.1

dependency_overrides:
  flutter_web_auth_2: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/