name: gachon_noti_front
description: "Gachon University Notice Service"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.3.0
  web: ^1.1.1
  pwa_install:
    git:
      url: https://github.com/jtmuller5/pwa_install.git
      ref: 82320a2
  url_launcher: ^6.3.1
  # flutter_svg: ^2.0.17
  flutter_auto_size_text: ^4.1.0
  package_info_plus: ^8.3.0
  intl: ^0.20.2
  http: ^1.4.0
  supabase_flutter: ^2.9.1
  get: ^4.7.2
  google_sign_in: ^6.3.0

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon_maskable_1024.png"
  remove_alpha_ios: true