name: RSS Crawler

on:
  schedule:
    - cron: "*/15 * * * *"  # 15분 간격
  workflow_dispatch:        # 수동 실행도 허용

jobs:
  rss-crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run crawler script
        env:
          APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
          APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
          APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
          APPWRITE_DATABASE_ID: ${{ secrets.APPWRITE_DATABASE_ID }}
          APPWRITE_POSTS_COLLECTION_ID: ${{ secrets.APPWRITE_POSTS_COLLECTION_ID }}
          APPWRITE_SUBSCRIPTIONS_COLLECTION_ID: ${{ secrets.APPWRITE_SUBSCRIPTIONS_COLLECTION_ID }}
          APPWRITE_USER_DEVICES_COLLECTION_ID: ${{ secrets.APPWRITE_USER_DEVICES_COLLECTION_ID }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: node index.js
